### ISSUE TITLE
Installing on FREEAPS Loop

### ISSUE THREAD

**Issue by miki3421** [julian-groen/xdrip-client-swift#1]
Hi, I tried to install on the FreeAps version of Loop

https://github.com/ivalkou/LoopWorkspace

and It's able to run only if the app is not installed yet.
The second time is crashing with the message.

EXC_BAD_ACCESS

attached you can find a detailed error. 
Thanks

<img width="1696" alt="Screenshot 2020-05-30 at 18 26 34" src="https://user-images.githubusercontent.com/42601846/83334158-d62f9400-a2a4-11ea-87da-48bc5854ded5.png">

**Comment by julian-groen** [comment]
Hi, I looked into it and couldn't find any connection with this client. As of now the only thing I can think of is that the FreeAps uses a different App Group identifier. Correct me if I'm wrong cuz im not familiar with this version of Loop.

Feel free to contact me if you still get an error.

**Comment by miki3421** [comment]
Hi Julian,
thank for you response,

FREEAPS it's a Loop's Workspace. It's just a different version of Loop.
May I ask you to try if the there is a way to integrate?
You can simulate the problem just with the simulator in Xcode.

I'don't think there is a lot of work.

here the appGroup.
It's the same for both app.

[image: image.png]

Have a nice day

Il giorno lun 1 giu 2020 alle ore 01:42 Julian Groen <
notifications@github.com> ha scritto:

**Comment by miki3421** [comment]
I found another error on the debugger:

*-canOpenURL: failed for URL: "xdrip://" - error: "This app is not allowed
to query for scheme xdrip"*


*may be can help.*



Il giorno lun 1 giu 2020 alle ore 08:11 Michele M <miki3421@gmail.com> ha
scritto:

**Comment by julian-groen** [comment]
Hi, I looked into it and didn't get any errors. The other error isn't really important if the main app of xdrip wil support those schemes it will work just fine. For the EXC_BAD_ACCESS error I think you have to look deeper into other dependencies cuz this client is just a framework and wil not mess with internal loop code like the one you showed me.

Hope you will find a solution to the problem if you need anything just contact me

**Comment by miki3421** [comment]
Are you able to start FreeAPS the second time on the simulator with out the
debug support?
The reason why I'm asking .. I'm able to install and run only if Xcode is
attached to the processes.
Have you tried to use just the simulator?

Now i'm not able to catch the error because the app is crashing with out
any errors.


Thanks


Il giorno lun 1 giu 2020 alle ore 13:29 Julian Groen <
notifications@github.com> ha scritto:

**Comment by julian-groen** [comment]
I will try. If you remove the client this error doesn't acquire?

**Comment by miki3421** [comment]
No if you remove the client one time is setup you can't do the rollback. 
You need to download again and recompile. 
For my tests I'm keeping two separate folders. 

did you reproduce the issue?

**Comment by julian-groen** [comment]
Alright, no everything kept working for me maybe try to reinstall everything?
If this error keeps happening please commit it to git so I can clone your setup.

**Comment by miki3421** [comment]
I tried .. nothing changed. 
How i can commit to git? Sorry but I'm not so expert in the matter of development. 
I tried to fork the Workspace but it's not tracing the changes in Loop folder. Do I need to create a separate Repository?

**Comment by julian-groen** [comment]
Try to google it, kinda hard to explain by text. You should also be able to just commit to the fork repo.

**Comment by miki3421** [comment]
Hi @julian-groen  thanks for your response. 
I tried to create https://github.com/miki3421/FREEAPS-with-Xdrip-Client with all folder of the project. However when I'm building the app I'm receiving this error. 

Gathering build details in /Users/mm/Documents/GitHub/FREEAPS-xdrip/FREEAPS-with-Xdrip-Client/Loop
fatal: not a git repository: /Users/mm/Documents/GitHub/FREEAPS-xdrip/FREEAPS-with-Xdrip-Client/Loop/../.git/modules/Loop
Command PhaseScriptExecution failed with a nonzero exit code

any ideas?

**Comment by julian-groen** [comment]
Can you send me a message on gitter.im?

**Comment by miki3421** [comment]
Done :)


Il giorno mer 10 giu 2020 alle ore 12:55 Julian Groen <
notifications@github.com> ha scritto:

**Comment by clvsjr9** [comment]
Hello,

  Some minor adjustments needs to be done in Info.plist files of: FreeAPS and xdripswift projects to be possible to click on BG value of HUD of Loop and then open xDrip app.

On xdripswift Project this is necessary: (Tell to Mr. Johan to do this minor detail)

![xdrip-Info](https://user-images.githubusercontent.com/12844781/85046838-5a1fc200-b167-11ea-978f-4c7b359bfe7f.jpg)

On FreeAPS Project this is necessary: (Julian, could you update the Readme file with a new paragraph on: Add xDrip as a CGM source to Loop in Xcode to complete?)

![Loop Info](https://user-images.githubusercontent.com/12844781/85046932-7de30800-b167-11ea-828d-1e627d5d8f20.jpg)

**Comment by julian-groen** [comment]
@clvsjr9 Thanks, I added the url scheme to the appUrl variable just as a placeholder no further intentions. So maybe they will add this feature in any further releases of xdrip.

@miki3421 Did you manage to solve the issue?

**Comment by miki3421** [comment]
@julian-groen  I've applied boths changes but the issue still present. 
When FREEAPS is starting is crashing, if is not connected to Xdrip Debugger.

**Comment by JohanDegraeve** [comment]
Hi, are you still waiting on a change in xdripswift ?

**Comment by julian-groen** [comment]
@JohanDegraeve no, not really. I just placed a placeholder for an appurl to xdrip nothing special there but there seems to be an bug with this FreeAPS version of Loop. I tried to look into it but couldn't find anything related with this client. So my advice to @miki3421 still would be to contact the developers of this FreeAPS version in order to fix it. If @miki3421 not already solved it himself.

**Comment by julian-groen** [comment]
@miki3421 I looked into the code of the normal version of Loop and found the exact same code. This client is running perfectly fine on my device for a couple of months. So in order to fix your issue I think you should update the FreeAPS code or move to a newer version of iOS. If this all doesn't work try to contact the FreeAPS Loop developers cause I still am 99% sure this issue isn't produced by this client.

Best of Luck!
